steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      env:
          - DOCKER_BUILDKIT=1
      args:
          [
              'build',
              '-t',
              'gcr.io/$PROJECT_ID/nominatim-fast:$COMMIT_SHA',
              '--build-arg',
              'PBF_URL=http://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf',
              '.',
          ]

    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/nominatim-fast:$COMMIT_SHA']

# Images to store in Container Registry
images:
    - 'gcr.io/$PROJECT_ID/nominatim-fast:$COMMIT_SHA'
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY
    machineType: 'E2_HIGHCPU_32'

tags:
    - nominatim-fast

# Timeout in seconds
timeout: '3600s'
