steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args:
          ['build', '-t', 'gcr.io/$PROJECT_ID/nominatim-fast:$COMMIT_SHA', '.']

    # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/nominatim-fast:$COMMIT_SHA']

# Images to store in Container Registry
images:
    - 'gcr.io/$PROJECT_ID/nominatim-fast:$COMMIT_SHA'
options:
    substitutionOption: ALLOW_LOOSE
    logging: CLOUD_LOGGING_ONLY

tags:
    - nominatim-fast

# Timeout in seconds
timeout: '1200s'
